version: '3'
services:
  overlay:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - APPLICATION_ENV=dev
    volumes:
      - ./logs:/var/log
      - ./src:/src
    ports:
      - 80:3000
    tty: true